_Obj = bmp_bottom.o bmpFileWrite.o

all: bmp_top bmpFileWrite
#add bmp_bottom to all: and in _Obj


bmp_top: bmp_top.c
	gcc -g -Wall -c bmp_top.c

bmpFileWrite: bmpFileWrite.c
	gcc -g -Wall -c bmpFileWrite.c
